#pragma once
enum CARD_TYPE
{
	UNKNOWN = -1,
	PASSPORT = 0,
	IDCARD = 1,
	HKMO_EXIT_ENTRY_PERMIT = 2,
	HKMO_HOME_RETURN_PERMIT = 3,
	TW_EXIT_ENTRY_PERMIT = 4,
	TW_HOME_RETURN_PERMIT = 5,
	Foreigner_Permanent_Residence_Permit=6,
	HKMOTW_IDCARD = 7,
	SMALL_CARD,
	ONE_LINE_CARD,
	THTEE_LINE_CARD,
	ANY_CARD
};